# .readthedocs.yaml
# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Build documentation with MkDocs
mkdocs:
  configuration: mkdocs.yml

# Optionally, you can specify an exact MkDocs version
python:
  install:
  - requirements: requirements.txt
